# Generated by Django 2.2.1 on 2019-06-07 16:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SetHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(max_length=2000)),
                ('card_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CardSet')),
            ],
        ),
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('front', models.CharField(max_length=2000)),
                ('back', models.CharField(max_length=2000)),
                ('history_front', models.CharField(default='', max_length=1200)),
                ('history_back', models.CharField(default='', max_length=1200)),
                ('last_trained_date_front', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_trained_date_back', models.DateTimeField(default=django.utils.timezone.now)),
                ('front_first', models.BooleanField(default=False)),
                ('marked', models.BooleanField(default=False)),
                ('card_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CardSet')),
            ],
        ),
        migrations.AddField(
            model_name='cardset',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Folder'),
        ),
    ]
